FROM python:3.9.6-alpine3.14@sha256:709505ac2ed5824430abb76db8cd24c45415aa1f267e133546977e0b18241d3e AS numpy-builder
RUN apk --update add --no-cache \
        cmake \
        g++ \
        git \
        make
RUN pip wheel --no-cache-dir -w wheels \
        Cython==0.29.23 \
        numpy==1.19.4


FROM numpy-builder AS pyarrow-builder
ARG ARROW_VERSION=3.0.0
ENV ARROW_HOME=/usr/local/lib/python3.9/site-packages/pyarrow
RUN pip install --no-cache-dir --no-index -f wheels Cython numpy
RUN git clone https://github.com/apache/arrow.git \
        --branch apache-arrow-${ARROW_VERSION} \
        --depth 1 \
    && mkdir /arrow/cpp/build \
    && cd /arrow/cpp/build \
    && cmake -D CMAKE_INSTALL_PREFIX=$ARROW_HOME -D ARROW_PYTHON=ON .. \
    && make -j $(nproc) \
    && make install \
    && cd /arrow/python \
    && python setup.py build_ext \
    && python setup.py install
RUN pip wheel --no-cache-dir -w wheels -f wheels \
        pyarrow==$ARROW_VERSION


FROM pyarrow-builder AS snowflake-connector-python-builder
ARG SNOWFLAKE_CONNECTOR_PYTHON_VERSION=2.4.6
RUN apk --update add --no-cache \
        cargo \
        gcc \
        libffi-dev \
        musl-dev \
        openssl-dev \
        python3-dev
RUN pip wheel -w wheels -f wheels \
        snowflake-connector-python==$SNOWFLAKE_CONNECTOR_PYTHON_VERSION
